// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfeypjinvrimlmqmeyjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZXlwamludnJpbWxtcW1leWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTg1MDgsImV4cCI6MjA2NzAzNDUwOH0.q9-WbI-NauoUjp3yC6wQ5BWgoLfeo9Mdzxm2yyuxhqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});